version: "2"

services:
  # a lighter drop in replacement for MySQL
  db:
    image: wodby/wordpress-mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 3306:3306

  # WordPress running on PHP-FPM
  wp:
    build:
      context: ./.docker-wp
    links:
      - db
    environment:
      - PHP_DOCROOT
      - PHP_SITE_NAME
      - PHP_HOST_NAME
      - PHP_SENDMAIL_PATH
      - PHP_XDEBUG_ENABLED
      - SITE_TITLE
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASS
      - DB_PREFIX
      - ADMIN_EMAIL
      - WP_DEBUG
      - WP_DEBUG_DISPLAY
      - WP_DEBUG_LOG
      - MULTISITE
      - VERSION
    volumes:
      # mounted in for normal wp operation, into hidden folder(s)
      - ./.wp:/var/www/html/
      - ./.plugins:/var/www/html/wp-content/plugins
      - ./.uploads:/var/www/html/wp-content/uploads
      - ./.themes:/var/www/html/wp-content/themes
      # custom theme or plugin folder, add all project specific folders here
      - ./../theme:/var/www/html/wp-content/themes/tortoisehare

  # Our Web Server serving files from the php-fpm container
  nginx:
    image: wodby/wordpress-nginx
    environment:
      - NGINX_SERVER_NAME
      - NGINX_UPSTREAM_NAME
      - NGINX_DOCROOT
    volumes_from:
      - wp
    ports:
      - "${WEB_PORT}:80"

  # Catch Mail for local development
  mailhog:
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_PORT}:8025"
