version: "2"

services:
  # a lighter drop in replacement for MySQL
  mariadb:
    image: wodby/wordpress-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  # WordPress running on PHP-FPM
  php:
    build:
      context: ./.docker-wp
    links:
      - mariadb
    environment:
      - PHP_DOCROOT
      - PHP_SITE_NAME
      - PHP_HOST_NAME
      - PHP_SENDMAIL_PATH
      - PHP_XDEBUG_ENABLED
      - SITE_TITLE
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASS
      - DB_PREFIX
      - ADMIN_EMAIL
      - WP_DEBUG
      - WP_DEBUG_DISPLAY
      - WP_DEBUG_LOG
      - MULTISITE
      - VERSION
    volumes:
      - ./../uploads:/var/www/html/wp-content/uploads
      - ./../themes:/var/www/html/wp-content/themes
      - ./../plugins:/var/www/html/wp-content/plugins
      - ./data:/data

  # Our Web Server
  nginx:
    image: wodby/wordpress-nginx
    environment:
      - NGINX_SERVER_NAME
      - NGINX_UPSTREAM_NAME
      - NGINX_DOCROOT
    volumes_from:
      - php
    ports:
      - "${WEB_PORT}:80"

  # Catch Mail for local development
  mailhog:
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_PORT}:8025"
